services:
  app:
    container_name: wishes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost:3000
      DATABASE_URL: data/prod.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
